# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'ServeSoup' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

pod 'SwiftKeychainWrapper', '~> 3.2'

  # Pods for ServeSoup

end
